apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petclinic
  namespace: argocd
spec:
  description: Spring PetClinic Microservices Project
  sourceRepos:
    - https://github.com/spring-petclinic-Group-4-DMI/spring-petclinic-Group-4-infra.git
  destinations:
    - namespace: petclinic-staging
      server: https://kubernetes.default.svc
    - namespace: petclinic-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
