apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genai-service.fullname" . }}-config
  labels:
    {{- include "genai-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
