apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "visits-service.fullname" . }}
  labels:
    {{- include "visits-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "visits-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "visits-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: visits-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "visits-service.fullname" . }}-config
