apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-server.fullname" . }}-config
  labels:
    {{- include "admin-server.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
