replicaCount: 1
image:
  repository: NEW_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/discovery-server
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 8761
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
configMap:
  SPRING_PROFILES_ACTIVE: kubernetes
